### ISSUE TITLE
Unsafe write into unreservered container

### ISSUE THREAD

**Issue by stevemk14ebr** [ocanty/remote_ptr#3]
https://github.com/ocanty/remote_ptr/blob/a9c106d479414ad43952061c73f30528990150fd/class_proxy.hpp#L31

This is unsafe and can crash/assert on some compilers as the allocation is not guaranteed to occur until you actually initialize elements through the vector interface. Memcpy and such into the vector right after a reserve may be invalid memory. 

Instead use:
```
// init to zero
instead use std::vector<blah> example(sizeof(valuetype), 0);
```

https://stackoverflow.com/questions/8228072/is-accessing-the-raw-pointer-after-stdvectorreserve-safe

**Comment by ocanty** [comment]
Fixed, thanks for the star and issue :)
